CREATE TABLE account 
    account_no TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    age TINYINT NOT NULL
    gender ENUM('male', 'female') NOT NULL,
    address TEXT NOT NULL,
    created_at DATETIME CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;